server:
  port: 8080
spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: email_user_web
  registry:
    address: zokeeper://192.168.75.99:2181
  consumer:
    check: false
    timeout: 10000
    retries: 3
