spring:
  datasource:
    url: jdbc:mysql:///user
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.75.99:2181
  protocol:
    port: -1
  consumer:
    check: false